replicaCount: 1

image:
  repository: nginxdemos/hello
  pullPolicy: IfNotPresent
  tag: "plain-text"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  host: "preview.local"

nameOverride: ""
fullnameOverride: ""
