name: Preview Comment

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  comment-preview-url:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Create or update PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            Preview environment:
            http://pr-${{ github.event.pull_request.number }}.localhost:8081